import { Asset } from "stellar-sdk"

export const mainnet = [
  new Asset("USD", "GBSTRUSD7IRX73RQZBL3RQUH6KS3O4NYFY3QCALDLZD77XMZOPWAVTUK"),
  new Asset("EURT", "GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S"),
  new Asset("CNY", "GAREELUB43IRHWEASCFBLKHURCGMHE5IF6XSE7EXDLACYHGRHM43RFOX")
]

export const testnet = [new Asset("EURT", "GD6CX65OOW5ADEDNOZS7MVQMIOPXT4ECFHJRFXAQFDUB4ARD4QUSVY6J")] as Asset[]
