image: node:10-jessie

stages:
  - setup
  - test
  - build
  - release

cache:
  key: npm-${CI_COMMIT_REF_SLUG}
  paths:
    - cache/
    - node_modules/
  policy: pull

prepare:
  stage: setup
  cache:
    key: npm-${CI_COMMIT_REF_SLUG}
    paths:
      - cache/
      - node_modules/
    policy: pull-push
  variables:
    npm_config_cache: $CI_PROJECT_DIR/cache/
  script:
    - echo $npm_config_cache
    - npm ci

lint:
  stage: test
  script:
    - npm run prettier:check

test:
  stage: test
  script:
    - npm test

build_web:
  stage: build
  script:
    - cd web/ && npm run build

# Note that the `npm run build:*` commands will automatically create a GitHub release and upload binaries
build_mac:
  stage: build
  artifacts:
    paths:
      - electron/dist
  script:
    - npm run build:mac -- --mac=zip
  only:
    - master

build_linux:
  stage: build
  artifacts:
    paths:
      - electron/dist
  script:
    - apt-get install -y rpm
    - npm run build:linux -- --linux=deb --linux=rpm
  only:
    - master
