image: node:10-jessie

stages:
  - setup
  - test
  - build
  - release

prepare:
  stage: setup
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules
    expire_in: 4 hours

test:
  stage: test
  script:
    - npm test

build_web:
  stage: build
  script:
    - cd web/ && npm run build

# Note that the `npm run build:*` commands will automatically create a GitHub release and upload binaries
build_mac:
  stage: build
  artifacts:
    paths:
      - electron/dist
  script:
    - npm run build:mac -- --mac=zip
  only:
    - master

build_linux:
  stage: build
  artifacts:
    paths:
      - electron/dist
  script:
    - sudo apt-get install rpm
    - npm run build:linux -- --linux=deb --linux=rpm
  only:
    - master
