image: node:10-jessie

stages:
  - test
  - build
  - release

test:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
  script:
    - npm ci
    - npm test

build_web:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
  script:
    - npm ci
    - cd web/ && npm run build

# Note that the `npm run build:*` commands will automatically create a GitHub release and upload binaries
build_mac:
  stage: build
  artifacts:
    paths:
      - electron/dist
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
  script:
    - npm ci
    - npm run build:mac -- --mac=zip
  only:
    - master

build_linux:
  stage: build
  artifacts:
    paths:
      - electron/dist
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
  script:
    - sudo apt-get install rpm
    - npm ci
    - npm run build:linux -- --linux=deb --linux=rpm
  only:
    - master
